"""crear_estructura_sistema

Revision ID: 575b8b8f7f89
Revises: 
Create Date: 2026-06-22 23:03:02.186691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <-- AÑADE ESTA LÍNEA AQUÍ


# revision identifiers, used by Alembic.
revision: str = '575b8b8f7f89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=False)
    op.create_table('tomainventariomadre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tomainventariomadre_estado'), 'tomainventariomadre', ['estado'], unique=False)
    op.create_table('subcategoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategoria_nombre'), 'subcategoria', ['nombre'], unique=False)
    op.create_table('zonainventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_toma_madre', sa.Integer(), nullable=False),
    sa.Column('nombre_zona', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_toma_madre'], ['tomainventariomadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonainventario_estado'), 'zonainventario', ['estado'], unique=False)
    op.create_index(op.f('ix_zonainventario_id_toma_madre'), 'zonainventario', ['id_toma_madre'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('referencia', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('subcategoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_codigo_barras'), 'producto', ['codigo_barras'], unique=False)
    op.create_table('conteozonadetalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad_fisica_contada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonainventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conteozonadetalle_id_producto'), 'conteozonadetalle', ['id_producto'], unique=False)
    op.create_index(op.f('ix_conteozonadetalle_id_zona'), 'conteozonadetalle', ['id_zona'], unique=False)
    op.create_table('inventariovalorizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('cantidad_sistema', sa.Integer(), nullable=False),
    sa.Column('costo_total_sistema', sa.Float(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventariovalorizado_id_producto'), 'inventariovalorizado', ['id_producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventariovalorizado_id_producto'), table_name='inventariovalorizado')
    op.drop_table('inventariovalorizado')
    op.drop_index(op.f('ix_conteozonadetalle_id_zona'), table_name='conteozonadetalle')
    op.drop_index(op.f('ix_conteozonadetalle_id_producto'), table_name='conteozonadetalle')
    op.drop_table('conteozonadetalle')
    op.drop_index(op.f('ix_producto_codigo_barras'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_zonainventario_id_toma_madre'), table_name='zonainventario')
    op.drop_index(op.f('ix_zonainventario_estado'), table_name='zonainventario')
    op.drop_table('zonainventario')
    op.drop_index(op.f('ix_subcategoria_nombre'), table_name='subcategoria')
    op.drop_table('subcategoria')
    op.drop_index(op.f('ix_tomainventariomadre_estado'), table_name='tomainventariomadre')
    op.drop_table('tomainventariomadre')
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
